# NumPy Real-World Practice Problems
### Practice with realistic scenarios!

These exercises simulate real data science tasks you'll encounter in projects.

**Tips:**
- Try to solve each problem on your own first
- Think about what operation you need (mean, sum, filter, etc.)
- Remember to use `axis=0` or `axis=1` when needed
- Solutions are at the bottom!

Let's go! 💪

In [2]:
import numpy as np
print("NumPy is ready!")

NumPy is ready!


---
## 📊 Problem 1: E-commerce Sales Analysis

You work for an online store. Here's the sales data for 4 products over 5 days:

Each row = one product, Each column = one day

In [3]:
sales_data = np.array([[120, 135, 148, 162, 175],  # Product A
                       [98, 105, 110, 115, 120],   # Product B
                       [200, 195, 210, 205, 220],  # Product C
                       [150, 160, 155, 170, 165]]) # Product D

print("Sales Data (Products × Days):")
print(sales_data)

Sales Data (Products × Days):
[[120 135 148 162 175]
 [ 98 105 110 115 120]
 [200 195 210 205 220]
 [150 160 155 170 165]]


### Task 1a: Find total sales for each product (across all 5 days)

In [4]:
# Your code here
total_per_product = np.sum(sales_data,axis=1)

print("Total sales per product:", total_per_product)

Total sales per product: [ 740  548 1030  800]


### Task 1b: Find total sales for each day (across all products)

In [5]:
# Your code here
total_per_day = np.sum(sales_data,axis=0)

print("Total sales per day:", total_per_day)

Total sales per day: [568 595 623 652 680]


### Task 1c: Which product had the highest average daily sales?

In [10]:
# Your code here
avg_sales = np.mean(sales_data,axis=1)
best_product = np.argmax(avg_sales)

print("Average sales per product:", avg_sales)
print("Best performing product index:", best_product)

Average sales per product: [148.  109.6 206.  160. ]
Best performing product index: 2


### Task 1d: Find all sales numbers greater than 150

In [11]:
# Your code here
high_sales = sales_data[sales_data>150]

print("Sales above 150:", high_sales)

Sales above 150: [162 175 200 195 210 205 220 160 155 170 165]


---
## 🎓 Problem 2: Student Performance Analysis

You're a teacher analyzing test scores. You have scores for 6 students across 4 exams.

In [12]:
# Each row = one student, Each column = one exam
exam_scores = np.array([[85, 92, 78, 88],  # Student 1
                        [76, 81, 85, 79],  # Student 2
                        [92, 95, 90, 94],  # Student 3
                        [68, 72, 75, 70],  # Student 4
                        [88, 85, 91, 87],  # Student 5
                        [95, 98, 96, 99]]) # Student 6

print("Exam Scores:")
print(exam_scores)

Exam Scores:
[[85 92 78 88]
 [76 81 85 79]
 [92 95 90 94]
 [68 72 75 70]
 [88 85 91 87]
 [95 98 96 99]]


### Task 2a: Calculate each student's average score

In [13]:
# Your code here
student_averages = np.mean(exam_scores,axis=1)

print("Each student's average:", student_averages)

Each student's average: [85.75 80.25 92.75 71.25 87.75 97.  ]


### Task 2b: Which exam was the hardest? (lowest average score)

In [16]:
# Your code here
exam_averages = np.mean(exam_scores,axis=0)
hardest_exam = np.argmin(exam_averages)

print("Average score per exam:", exam_averages)
print("Hardest exam (index):", hardest_exam)

Average score per exam: [84.         87.16666667 85.83333333 86.16666667]
Hardest exam (index): 0


### Task 2c: How many students scored above 85 on average?

In [17]:
# Your code here (hint: use boolean indexing and count)
count_above_85 = np.sum(exam_averages>85)

print("Number of students with avg > 85:", count_above_85)

Number of students with avg > 85: 3


### Task 2d: Give a 5-point bonus to all scores below 80

In [19]:
# Your code here (be careful not to modify the original!)
adjusted_scores = exam_scores.copy()  # Make a copy first
adjusted_scores[adjusted_scores<80] +=5

print("Adjusted scores:")
print(adjusted_scores)

Adjusted scores:
[[85 92 83 88]
 [81 81 85 84]
 [92 95 90 94]
 [73 77 80 75]
 [88 85 91 87]
 [95 98 96 99]]


---
## 💰 Problem 3: Monthly Expenses Tracker

Track your monthly expenses across 3 months in different categories.

In [20]:
# Each row = category, Each column = month
expenses = np.array([[1200, 1250, 1300],  # Rent
                     [400, 450, 380],     # Food
                     [150, 200, 180],     # Transport
                     [80, 90, 100],       # Entertainment
                     [200, 180, 220]])    # Utilities

categories = ['Rent', 'Food', 'Transport', 'Entertainment', 'Utilities']
print("Monthly Expenses:")
print(expenses)

Monthly Expenses:
[[1200 1250 1300]
 [ 400  450  380]
 [ 150  200  180]
 [  80   90  100]
 [ 200  180  220]]


### Task 3a: What's the total spending per month?

In [21]:
# Your code here
monthly_total = np.sum(expenses,axis=0)

print("Total per month:", monthly_total)

Total per month: [2030 2170 2180]


### Task 3b: What's the average spending per category over 3 months?

In [22]:
# Your code here
category_avg = np.mean(expenses,axis=1)

for i, cat in enumerate(categories):
    print(f"{cat}: ${category_avg[i]:.2f}")

Rent: $1250.00
Food: $410.00
Transport: $176.67
Entertainment: $90.00
Utilities: $200.00


### Task 3c: What percentage of total expenses is Rent?

In [25]:
# Your code here
total_expenses = np.sum(expenses)
rent_total = np.sum(expenses[0])
rent_percentage = (rent_total/total_expenses)*100

print(f"Rent is {rent_percentage:.1f}% of total expenses")

Rent is 58.8% of total expenses


---
## 🏃 Problem 4: Fitness Tracker - Heart Rate Data

You recorded your heart rate (BPM) during a 7-day workout plan.

In [26]:
# Heart rate measurements (BPM) for 7 days
heart_rate = np.array([72, 85, 78, 92, 88, 95, 80])

print("Heart rate (BPM) for 7 days:", heart_rate)

Heart rate (BPM) for 7 days: [72 85 78 92 88 95 80]


### Task 4a: What's your average heart rate?

In [27]:
# Your code here
avg_hr = np.mean(heart_rate)

print(f"Average heart rate: {avg_hr:.1f} BPM")

Average heart rate: 84.3 BPM


### Task 4b: On which days did your heart rate exceed 85 BPM?

In [32]:
# Your code here (hint: use np.where())
high_hr_days = np.where(heart_rate==85)

print("Days with HR > 85:", high_hr_days)

Days with HR > 85: (array([1]),)


### Task 4c: What's the difference between max and min heart rate?

In [33]:
# Your code here
hr_range = np.max(heart_rate)-np.min(heart_rate)

print(f"Heart rate range: {hr_range} BPM")

Heart rate range: 23 BPM


---
## 🌡️ Problem 5: Weather Data Analysis

Temperature data (°C) for 5 cities over one week.

In [34]:
# Each row = city, Each column = day of week
temperatures = np.array([[28, 30, 29, 31, 32, 30, 28],  # City A
                        [15, 17, 16, 18, 19, 17, 16],  # City B
                        [22, 24, 23, 25, 26, 24, 23],  # City C
                        [35, 36, 37, 38, 37, 36, 35],  # City D
                        [10, 12, 11, 13, 14, 12, 11]]) # City E

cities = ['City A', 'City B', 'City C', 'City D', 'City E']
print("Temperature data (°C):")
print(temperatures)

Temperature data (°C):
[[28 30 29 31 32 30 28]
 [15 17 16 18 19 17 16]
 [22 24 23 25 26 24 23]
 [35 36 37 38 37 36 35]
 [10 12 11 13 14 12 11]]


### Task 5a: Which city has the highest average temperature?

In [36]:
# Your code here
avg_temps = np.mean(temperatures,axis=1)
hottest_city_index = np.argmax(avg_temps)

print("Average temperatures:", avg_temps)
print(f"Hottest city: {cities[hottest_city_index]}")

Average temperatures: [29.71428571 16.85714286 23.85714286 36.28571429 11.85714286]
Hottest city: City D


### Task 5b: What was the coldest day across all cities?

In [38]:
# Your code here
coldest_temp = np.min(temperatures)

print(f"Coldest temperature recorded: {coldest_temp}°C")

Coldest temperature recorded: 10°C


### Task 5c: Convert all temperatures to Fahrenheit

In [39]:
# Your code here
temps_fahrenheit = (temperatures *9/5) + 32

print("Temperatures in Fahrenheit:")
print(temps_fahrenheit)

Temperatures in Fahrenheit:
[[ 82.4  86.   84.2  87.8  89.6  86.   82.4]
 [ 59.   62.6  60.8  64.4  66.2  62.6  60.8]
 [ 71.6  75.2  73.4  77.   78.8  75.2  73.4]
 [ 95.   96.8  98.6 100.4  98.6  96.8  95. ]
 [ 50.   53.6  51.8  55.4  57.2  53.6  51.8]]


### Task 5d: How many temperature readings were above 25°C?

In [41]:
# Your code here
count_above_25 = np.sum(temperatures>25)

print(f"Number of readings above 25°C: {count_above_25}")

Number of readings above 25°C: 15


---
## 🎮 Problem 6: Gaming Statistics

You play 3 different games and track your scores over 5 sessions.

In [3]:
# Each row = game, Each column = session
game_scores = np.array([[1200, 1450, 1350, 1500, 1600],  # Game 1
                       [850, 900, 920, 950, 980],       # Game 2
                       [2100, 2200, 2050, 2300, 2400]]) # Game 3

print("Game Scores:")
print(game_scores)

Game Scores:
[[1200 1450 1350 1500 1600]
 [ 850  900  920  950  980]
 [2100 2200 2050 2300 2400]]


### Task 6a: What's your highest score in each game?

In [5]:
# Your code here
high_scores = np.max(game_scores, axis=1)

print("Highest scores per game:", high_scores)

Highest scores per game: [1600  980 2400]


### Task 6b: Calculate the improvement from first to last session for each game

In [6]:
# Your code here
improvement = game_scores[:,-1]-game_scores[:,0]

print("Score improvement per game:", improvement)

Score improvement per game: [400 130 300]


### Task 6c: Which game shows the most consistent performance? (lowest std deviation)

In [7]:
# Your code here
std_devs = np.std(game_scores, axis=1)
most_consistent = np.argmin(std_devs)

print("Standard deviation per game:", std_devs)
print(f"Most consistent game (index): {most_consistent}")

Standard deviation per game: [136.38181697  44.27188724 128.06248475]
Most consistent game (index): 1


---
## 💊 Problem 7: Medicine Dosage Tracker

Track medication doses (mg) taken over 10 days.

In [8]:
# Daily dosage in mg
dosage = np.array([50, 50, 75, 75, 75, 100, 100, 100, 75, 50])

print("Daily dosage (mg):", dosage)

Daily dosage (mg): [ 50  50  75  75  75 100 100 100  75  50]


### Task 7a: What's the total medication consumed over 10 days?

In [9]:
# Your code here
total_dosage = np.sum(dosage)

print(f"Total dosage: {total_dosage} mg")

Total dosage: 750 mg


### Task 7b: What's the average daily dose?

In [10]:
# Your code here
avg_dosage = np.mean(dosage)

print(f"Average daily dose: {avg_dosage} mg")

Average daily dose: 75.0 mg


### Task 7c: On which days was the dose 100mg or more?

In [11]:
# Your code here
high_dose_days = np.argwhere(dosage>=100)

print("Days with 100mg+ dose:", high_dose_days)

Days with 100mg+ dose: [[5]
 [6]
 [7]]


---
## 📱 Problem 8: Social Media Engagement

Track likes, comments, and shares for your 5 posts.

In [12]:
# Each row = [likes, comments, shares]
engagement = np.array([[120, 15, 8],   # Post 1
                      [450, 32, 25],  # Post 2
                      [89, 7, 3],     # Post 3
                      [310, 28, 18],  # Post 4
                      [520, 45, 35]]) # Post 5

print("Engagement [likes, comments, shares]:")
print(engagement)

Engagement [likes, comments, shares]:
[[120  15   8]
 [450  32  25]
 [ 89   7   3]
 [310  28  18]
 [520  45  35]]


### Task 8a: What's the total engagement (sum of all metrics) for each post?

In [13]:
# Your code here
total_engagement = np.sum(engagement)

print("Total engagement per post:", total_engagement)

Total engagement per post: 1705


### Task 8b: Which post got the most likes?

In [15]:
# Your code here (hint: likes are in column 0)
most_liked_post = np.argmax(engagement[:,0])

print(f"Post with most likes: Post {most_liked_post + 1}")

Post with most likes: Post 5


### Task 8c: What's the average number of comments across all posts?

In [16]:
# Your code here (comments are in column 1)
avg_comments = np.mean(engagement[:,1])

print(f"Average comments: {avg_comments:.1f}")

Average comments: 25.4


---
---
# 🎯 SOLUTIONS

Scroll down only after attempting all problems!

## Problem 1 Solutions

In [ ]:
# Task 1a
total_per_product = np.sum(sales_data, axis=1)
print("1a:", total_per_product)

In [ ]:
# Task 1b
total_per_day = np.sum(sales_data, axis=0)
print("1b:", total_per_day)

In [ ]:
# Task 1c
avg_sales = np.mean(sales_data, axis=1)
best_product = np.argmax(avg_sales)
print("1c: Averages:", avg_sales)
print("Best product:", best_product)

In [ ]:
# Task 1d
high_sales = sales_data[sales_data > 150]
print("1d:", high_sales)

## Problem 2 Solutions

In [ ]:
# Task 2a
student_averages = np.mean(exam_scores, axis=1)
print("2a:", student_averages)

In [ ]:
# Task 2b
exam_averages = np.mean(exam_scores, axis=0)
hardest_exam = np.argmin(exam_averages)
print("2b: Exam averages:", exam_averages)
print("Hardest exam:", hardest_exam)

In [ ]:
# Task 2c
count_above_85 = np.sum(student_averages > 85)
print("2c:", count_above_85)

In [ ]:
# Task 2d
adjusted_scores = exam_scores.copy()
adjusted_scores[adjusted_scores < 80] += 5
print("2d:")
print(adjusted_scores)

## Problem 3 Solutions

In [ ]:
# Task 3a
monthly_total = np.sum(expenses, axis=0)
print("3a:", monthly_total)

In [ ]:
# Task 3b
category_avg = np.mean(expenses, axis=1)
print("3b:", category_avg)

In [ ]:
# Task 3c
total_expenses = np.sum(expenses)
rent_total = np.sum(expenses[0])  # First row is rent
rent_percentage = (rent_total / total_expenses) * 100
print(f"3c: Rent is {rent_percentage:.1f}% of total")

## Problem 4 Solutions

In [ ]:
# Task 4a
avg_hr = np.mean(heart_rate)
print(f"4a: {avg_hr:.1f} BPM")

In [ ]:
# Task 4b
high_hr_days = np.where(heart_rate > 85)[0]
print("4b:", high_hr_days)

In [ ]:
# Task 4c
hr_range = np.max(heart_rate) - np.min(heart_rate)
print("4c:", hr_range)

## Problem 5 Solutions

In [ ]:
# Task 5a
avg_temps = np.mean(temperatures, axis=1)
hottest_city_index = np.argmax(avg_temps)
print("5a:", avg_temps)
print("Hottest:", cities[hottest_city_index])

In [ ]:
# Task 5b
coldest_temp = np.min(temperatures)
print("5b:", coldest_temp)

In [ ]:
# Task 5c
temps_fahrenheit = (temperatures * 9/5) + 32
print("5c:")
print(temps_fahrenheit)

In [ ]:
# Task 5d
count_above_25 = np.sum(temperatures > 25)
print("5d:", count_above_25)

## Problem 6 Solutions

In [ ]:
# Task 6a
high_scores = np.max(game_scores, axis=1)
print("6a:", high_scores)

In [ ]:
# Task 6b
improvement = game_scores[:, -1] - game_scores[:, 0]
print("6b:", improvement)

In [ ]:
# Task 6c
std_devs = np.std(game_scores, axis=1)
most_consistent = np.argmin(std_devs)
print("6c:", std_devs)
print("Most consistent:", most_consistent)

## Problem 7 Solutions

In [ ]:
# Task 7a
total_dosage = np.sum(dosage)
print("7a:", total_dosage)

In [ ]:
# Task 7b
avg_dosage = np.mean(dosage)
print("7b:", avg_dosage)

In [ ]:
# Task 7c
high_dose_days = np.where(dosage >= 100)[0]
print("7c:", high_dose_days)

## Problem 8 Solutions

In [ ]:
# Task 8a
total_engagement = np.sum(engagement, axis=1)
print("8a:", total_engagement)

In [ ]:
# Task 8b
most_liked_post = np.argmax(engagement[:, 0])
print("8b: Post", most_liked_post + 1)

In [ ]:
# Task 8c
avg_comments = np.mean(engagement[:, 1])
print(f"8c: {avg_comments:.1f}")

---
## 🎉 Excellent Work!

You've completed real-world NumPy problems!

**What you practiced:**
- ✅ Using `axis=0` and `axis=1` correctly
- ✅ Boolean indexing and filtering
- ✅ Statistical operations (mean, sum, std, etc.)
- ✅ Array manipulation
- ✅ Real data scenarios

**Next steps:**
- Create your own datasets and analyze them
- Move on to Pandas (it builds on NumPy!)
- Try combining multiple operations

Keep practicing! 💪🚀