# NumPy Practice Exercises
### Practice to Master NumPy!

**Instructions:**
- Work through each exercise in order
- Write your code in the cells provided
- Run each cell to see if your answer is correct
- Solutions are provided at the end, but try solving on your own first!

Let's get started! 🚀

In [1]:
# First, let's import NumPy
import numpy as np
print("NumPy version:", np.__version__)

NumPy version: 2.1.3


---
## Section 1: Array Creation
Learn to create arrays in different ways

### Exercise 1: Create a 1D array
Create an array with numbers from 0 to 9

In [3]:
# Your code here
arr1 =np.arange(1,11)

print(arr1)

[ 1  2  3  4  5  6  7  8  9 10]


### Exercise 2: Create a zeros array
Create a 3x3 array filled with zeros

In [8]:
# Your code here
zeros_array = np.zeros(11)

print(zeros_array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


### Exercise 3: Create an ones array
Create a 2x4 array filled with ones

In [9]:
# Your code here
ones_array = np.ones(10)

print(ones_array)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


### Exercise 4: Create an identity matrix
Create a 5x5 identity matrix

In [10]:
# Your code here
id = np.arange(1,26)
identity=id.reshape(5,5)

print(identity)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


### Exercise 5: Create array with range
Create an array with values from 10 to 50 with step of 5

In [12]:
# Your code here
range_array = np.arange(10,51,5)

print(range_array)

[10 15 20 25 30 35 40 45 50]


### Exercise 6: Create random array
Create a 3x3 array with random integers between 1 and 100

In [21]:
# Your code here
random_array = np.random.randint(1,10, size=(3))

print(random_array)

[8 2 4]


---
## Section 2: Array Indexing & Slicing
Learn to access and extract parts of arrays

In [22]:
# This is our sample array for exercises 7-12
arr = np.array([[1, 2, 3, 4, 5],
                [6, 7, 8, 9, 10],
                [11, 12, 13, 14, 15],
                [16, 17, 18, 19, 20]])
print("Sample Array:")
print(arr)

Sample Array:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


### Exercise 7: Access single element
Extract the element at row 2, column 3 (remember: indexing starts at 0!)

In [23]:
# Your code here
element = arr[2,3]

print(element)

14


### Exercise 8: Extract first row
Get the entire first row

In [24]:
# Your code here
first_row = arr[0]

print(first_row)

[1 2 3 4 5]


### Exercise 9: Extract last column
Get the entire last column

In [25]:
# Your code here
last_column = arr[0:4,4]

print(last_column)

[ 5 10 15 20]


### Exercise 10: Extract sub-array
Extract a 2x2 sub-array from rows 1-2 and columns 1-2

In [26]:
# Your code here
sub_array = arr[1:3,1:3]

print(sub_array)

[[ 7  8]
 [12 13]]


### Exercise 11: Boolean indexing
Extract all elements from arr that are greater than 10

In [30]:
# Your code here
greater_than_10 = arr>10
arr2=arr[greater_than_10]

print(greater_than_10)
print(arr2)

[[False False False False False]
 [False False False False False]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]
[11 12 13 14 15 16 17 18 19 20]


### Exercise 12: Conditional extraction
Extract all even numbers from arr

In [32]:
# Your code here
even_numbers = arr[arr%2==0]


print(even_numbers)

[ 2  4  6  8 10 12 14 16 18 20]


---
## Section 3: Array Operations
Perform mathematical operations on arrays

### Exercise 13: Element-wise addition
Add these two arrays element by element

In [33]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([10, 20, 30, 40, 50])

# Your code here
result = a+b

print(result)

[11 22 33 44 55]


### Exercise 14: Scalar multiplication
Multiply array 'a' by 3

In [35]:
# Your code here
result = a*3

print(result)

[ 3  6  9 12 15]


### Exercise 15: Square each element
Calculate the square of each element in array 'a'

In [36]:
# Your code here
squared = a**2

print(squared)

[ 1  4  9 16 25]


### Exercise 16: Statistical operations
Calculate mean, median, and standard deviation of the data array

In [42]:
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Your code here
mean = data.mean()
median = np.median(data)
std_dev = data.std()

print(f"Mean: {mean}")
print(f"Median: {median}")
print(f"Standard Deviation: {std_dev}")

Mean: 5.5
Median: 5.5
Standard Deviation: 2.8722813232690143


### Exercise 17: Min and Max
Find the minimum and maximum values in the data array

In [43]:
# Your code here
min_val = np.min(data)
max_val = np.max(data)

print(f"Minimum: {min_val}")
print(f"Maximum: {max_val}")

Minimum: 1
Maximum: 10


### Exercise 18: Sum and Product
Calculate the sum and product of all elements in the array [1, 2, 3, 4, 5]

In [49]:
arr = np.array([1, 2, 3, 4, 5])

# Your code here
total_sum = np.sum(arr)
total_product = np.prod(arr)

print(f"Sum: {total_sum}")
print(f"Product: {total_product}")

Sum: 15
Product: 120


---
## Section 4: Array Reshaping
Change the shape and structure of arrays

### Exercise 19: Reshape 1D to 2D
Reshape the 1D array into a 3x4 array

In [50]:
arr_1d = np.arange(12)
print("Original array:", arr_1d)

# Your code here
arr_2d = arr_1d.reshape(3,4)

print("Reshaped array:")
print(arr_2d)

Original array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


### Exercise 20: Flatten array
Flatten the 2D array into 1D

In [53]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("Original 2D array:")
print(arr_2d)

# Your code here
flattened = arr_2d.flatten()

print("Flattened array:", flattened)

Original 2D array:
[[1 2 3]
 [4 5 6]]
Flattened array: [1 2 3 4 5 6]


### Exercise 21: Transpose
Transpose the matrix (swap rows and columns)

In [54]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])
print("Original matrix:")
print(matrix)

# Your code here
transposed = matrix.T

print("Transposed matrix:")
print(transposed)

Original matrix:
[[1 2 3]
 [4 5 6]]
Transposed matrix:
[[1 4]
 [2 5]
 [3 6]]


### Exercise 22: Vertical stacking
Stack arr1 and arr2 vertically (one on top of the other)

In [55]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Your code here
v_stacked = np.vstack((arr1,arr2))

print(v_stacked)

[[1 2 3]
 [4 5 6]]


### Exercise 23: Horizontal stacking
Stack arr1 and arr2 horizontally (side by side)

In [56]:
# Your code here
h_stacked = np.hstack((arr1,arr2))

print(h_stacked)

[1 2 3 4 5 6]


---
## Section 5: Real-World Problems
Apply NumPy to practical scenarios

### Exercise 24: Temperature Conversion
Convert Celsius temperatures to Fahrenheit

Formula: F = (C × 9/5) + 32

In [59]:
celsius = np.array([0, 10, 20, 30, 40])

# Your code here
fahrenheit = (celsius*9/5)+32

print("Celsius:", celsius)
print("Fahrenheit:", fahrenheit)

Celsius: [ 0 10 20 30 40]
Fahrenheit: [ 32.  50.  68.  86. 104.]


### Exercise 25: Student Grades Analysis
Calculate the average grade for each student (each row represents one student's grades)

In [61]:
grades = np.array([[85, 90, 78],   # Student 1
                   [92, 88, 95],   # Student 2
                   [70, 75, 80]])  # Student 3

# Your code here (hint: use axis parameter)
avg_grades = np.mean(grades,axis=1)

print("Average grades for each student:", avg_grades)

Average grades for each student: [84.33333333 91.66666667 75.        ]


### Exercise 26: Sales Analysis
Find total sales for each product across all months

In [62]:
sales = np.array([[100, 150, 200],  # Product 1 sales (3 months)
                  [80, 90, 110],     # Product 2 sales
                  [120, 130, 140]])  # Product 3 sales

# Your code here
total_sales = np.sum(sales,axis=1)

print("Total sales per product:", total_sales)

Total sales per product: [450 280 390]


### Exercise 27: Data Normalization
Normalize the data to have values between 0 and 1

Formula: (x - min) / (max - min)

In [64]:
data = np.array([10, 20, 30, 40, 50])

# Your code here
normalized = (data-np.min(data))/(np.max(data)- min(data))

print("Original data:", data)
print("Normalized data:", normalized)

Original data: [10 20 30 40 50]
Normalized data: [0.   0.25 0.5  0.75 1.  ]


### Exercise 28: Replace values with condition
Replace all values less than 5 with 0 in the array

In [65]:
arr = np.array([1, 6, 3, 8, 2, 9, 4, 7, 5])
print("Original array:", arr)

# Your code here
arr[arr < 5] = 0

print("Modified array:", arr)

Original array: [1 6 3 8 2 9 4 7 5]
Modified array: [0 6 0 8 0 9 0 7 5]


### Exercise 29: Matrix Multiplication
Multiply these two matrices

In [68]:
matrix1 = np.array([[1, 2],
                    [3, 4]])

matrix2 = np.array([[5, 6],
                    [7, 8]])

# Your code here (hint: use np.dot() or @ operator)
result = np.dot(matrix1,matrix2)

print("Result of matrix multiplication:")
print(result)

Result of matrix multiplication:
[[19 22]
 [43 50]]


### Exercise 30: Find unique values
Find all unique values in the array and count how many times each appears

In [70]:
arr = np.array([1, 2, 2, 3, 3,3, 3, 4, 4, 4, 4,4])

# Your code here
unique_vals, counts = np.unique(arr, return_counts=True)

print("Unique values:", unique_vals)
print("Counts:", counts)

Unique values: [1 2 3 4]
Counts: [1 2 4 5]


---
---
# 🎯 Solutions

**Try to solve all exercises above before looking at these solutions!**

## Section 1 Solutions

In [ ]:
# Exercise 1
arr1 = np.arange(10)
print("Exercise 1:", arr1)

In [ ]:
# Exercise 2
zeros_array = np.zeros((3, 3))
print("Exercise 2:\n", zeros_array)

In [ ]:
# Exercise 3
ones_array = np.ones((2, 4))
print("Exercise 3:\n", ones_array)

In [ ]:
# Exercise 4
identity = np.eye(5)
print("Exercise 4:\n", identity)

In [ ]:
# Exercise 5
range_array = np.arange(10, 51, 5)
print("Exercise 5:", range_array)

In [ ]:
# Exercise 6
random_array = np.random.randint(1, 101, size=(3, 3))
print("Exercise 6:\n", random_array)

## Section 2 Solutions

In [ ]:
arr = np.array([[1, 2, 3, 4, 5],
                [6, 7, 8, 9, 10],
                [11, 12, 13, 14, 15],
                [16, 17, 18, 19, 20]])

In [ ]:
# Exercise 7
element = arr[2, 3]
print("Exercise 7:", element)

In [ ]:
# Exercise 8
first_row = arr[0]
print("Exercise 8:", first_row)

In [ ]:
# Exercise 9
last_column = arr[:, -1]
print("Exercise 9:", last_column)

In [ ]:
# Exercise 10
sub_array = arr[1:3, 1:3]
print("Exercise 10:\n", sub_array)

In [ ]:
# Exercise 11
greater_than_10 = arr[arr > 10]
print("Exercise 11:", greater_than_10)

In [ ]:
# Exercise 12
even_numbers = arr[arr % 2 == 0]
print("Exercise 12:", even_numbers)

## Section 3 Solutions

In [ ]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([10, 20, 30, 40, 50])

In [ ]:
# Exercise 13
result = a + b
print("Exercise 13:", result)

In [ ]:
# Exercise 14
result = a * 3
print("Exercise 14:", result)

In [ ]:
# Exercise 15
squared = a ** 2
print("Exercise 15:", squared)

In [ ]:
# Exercise 16
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
mean = np.mean(data)
median = np.median(data)
std_dev = np.std(data)
print(f"Exercise 16: Mean={mean}, Median={median}, Std={std_dev}")

In [ ]:
# Exercise 17
min_val = np.min(data)
max_val = np.max(data)
print(f"Exercise 17: Min={min_val}, Max={max_val}")

In [ ]:
# Exercise 18
arr = np.array([1, 2, 3, 4, 5])
total_sum = np.sum(arr)
total_product = np.prod(arr)
print(f"Exercise 18: Sum={total_sum}, Product={total_product}")

## Section 4 Solutions

In [ ]:
# Exercise 19
arr_1d = np.arange(12)
arr_2d = arr_1d.reshape(3, 4)
print("Exercise 19:\n", arr_2d)

In [ ]:
# Exercise 20
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
flattened = arr_2d.flatten()
print("Exercise 20:", flattened)

In [ ]:
# Exercise 21
matrix = np.array([[1, 2, 3], [4, 5, 6]])
transposed = matrix.T
print("Exercise 21:\n", transposed)

In [ ]:
# Exercise 22
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
v_stacked = np.vstack((arr1, arr2))
print("Exercise 22:\n", v_stacked)

In [ ]:
# Exercise 23
h_stacked = np.hstack((arr1, arr2))
print("Exercise 23:", h_stacked)

## Section 5 Solutions

In [ ]:
# Exercise 24
celsius = np.array([0, 10, 20, 30, 40])
fahrenheit = (celsius * 9/5) + 32
print("Exercise 24:", fahrenheit)

In [ ]:
# Exercise 25
grades = np.array([[85, 90, 78], [92, 88, 95], [70, 75, 80]])
avg_grades = np.mean(grades, axis=1)
print("Exercise 25:", avg_grades)

In [ ]:
# Exercise 26
sales = np.array([[100, 150, 200], [80, 90, 110], [120, 130, 140]])
total_sales = np.sum(sales, axis=1)
print("Exercise 26:", total_sales)

In [ ]:
# Exercise 27
data = np.array([10, 20, 30, 40, 50])
normalized = (data - np.min(data)) / (np.max(data) - np.min(data))
print("Exercise 27:", normalized)

In [ ]:
# Exercise 28
arr = np.array([1, 6, 3, 8, 2, 9, 4, 7, 5])
arr[arr < 5] = 0
print("Exercise 28:", arr)

In [ ]:
# Exercise 29
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])
result = np.dot(matrix1, matrix2)
# Alternative: result = matrix1 @ matrix2
print("Exercise 29:\n", result)

In [ ]:
# Exercise 30
arr = np.array([1, 2, 2, 3, 3, 3, 4, 4, 4, 4])
unique_vals, counts = np.unique(arr, return_counts=True)
print("Exercise 30: Values:", unique_vals, "Counts:", counts)

---
## 🎉 Congratulations!

You've completed all 30 NumPy exercises! 

**Next Steps:**
- Try creating your own exercises
- Work on a small project using NumPy
- Learn Pandas (it's built on NumPy!)

Keep practicing! 💪