In [1]:
import numpy as np

In [2]:
#problem1
arr=np.arange(1,21)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [3]:
#problem2
arr=np.zeros(9).reshape(3,3)
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [4]:
#problem3
arr=np.full((5,5),7)
arr

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

In [5]:
#problem4
arr=np.arange(10,51,2)
arr

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [6]:
#problem5
arr=np.random.randint(1,101,size=10)
arr



array([12, 90, 95, 10,  3, 66, 45, 29, 16, 64], dtype=int32)

In [7]:
#problem6
arr=np.arange(1,10).reshape(3,3)
arr.ndim

2

In [8]:
#problem7
arr=np.arange(1,13).reshape(4,3)
arr.shape

(4, 3)

In [9]:
#problem8
arr=np.arange(1,10)
arr.dtype

dtype('int64')

In [10]:
#problem9
arr=np.linspace(4,6,9).reshape(3,3)
arr.dtype

dtype('float64')

In [11]:
#problem10
arr=np.arange(1,10)
arr.size

9

In [12]:
#problem11
arr=np.arange(1,26).reshape(5,5)
arr[2]

array([11, 12, 13, 14, 15])

In [13]:
#problem12
arr=np.arange(1,26).reshape(5,5)
arr[0:,0]

array([ 1,  6, 11, 16, 21])

In [14]:
#problem13
arr=np.arange(1,26).reshape(5,5)
arr[4]=1
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [ 1,  1,  1,  1,  1]])

In [15]:
#problem14
arr=np.arange(1,26)
arr[2:9:2]

array([3, 5, 7, 9])

In [16]:
#problem15
arr=np.arange(1,17).reshape(4,4)
np.diag(arr)

array([ 1,  6, 11, 16])

In [17]:
#problem16
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr1+arr2

array([5, 7, 9])

In [18]:
#problem17
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr1*arr2

array([ 4, 10, 18])

In [19]:
#problem18
arr=np.arange(1,17).reshape(4,4)
arr*5

array([[ 5, 10, 15, 20],
       [25, 30, 35, 40],
       [45, 50, 55, 60],
       [65, 70, 75, 80]])

In [20]:
#problem19
arr1=np.array([1,2,3])
np.square(arr1)

array([1, 4, 9])

In [21]:
#problem20
arr=np.arange(1,17).reshape(4,4)
np.sum(arr)

np.int64(136)

In [22]:
#problem21
arr=np.arange(1,13).reshape(3,4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [23]:
#problem22
arr=np.arange(1,17).reshape(4,4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [24]:
#problem23
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
np.vstack((arr1,arr2))

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
#problem24
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
np.hstack((arr1,arr2))

array([1, 2, 3, 4, 5, 6])

In [26]:
#problem25
arr=np.arange(1,17).reshape(4,4)
arr.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [27]:
#problem26
n=arr=np.arange(1,51)
bolean=n>30
n[bolean]


array([31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
       48, 49, 50])

In [28]:
#problem27
arr=np.arange(1,51)
arr[0:9]=0
arr

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [29]:
#problem28
arr=np.random.randint(1,51,size=10)
even=arr[arr%2==0]
even



array([32,  4, 42, 48, 44], dtype=int32)

In [30]:
#problem29
arr=np.arange(-7,6)
arr[0:7]=0
arr

array([0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 3, 4, 5])

In [31]:
#problem30
arr=np.arange(1,17).reshape(4,4)
b=np.mean(arr)
c=arr<b
arr[c]



array([1, 2, 3, 4, 5, 6, 7, 8])

In [32]:
#problem31
arr=np.eye(5)
arr

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [33]:
#problem32
arr=np.arange(1,17).reshape(4,4)
arr.T

array([[ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15],
       [ 4,  8, 12, 16]])

In [34]:
#problem33
arr=np.arange(1,17).reshape(4,4)
d=np.linalg.det(arr)
d

np.float64(0.0)

In [35]:
#problem34
arr1=np.arange(1,5).reshape(2,2)
arr2=np.arange(5,9).reshape(2,2)
arr1.dot(arr2)

array([[19, 22],
       [43, 50]])

In [36]:
#problem35
arr=np.linspace(0,1,10)
arr

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])