In [1]:
import numpy as np

In [2]:
arr=np.array([10,20,30,40,50])
arr

array([10, 20, 30, 40, 50])

In [36]:
arr=np.array([[1,2,3],[4,5,6],[7,200,9]])
arr

array([[  1,   2,   3],
       [  4,   5,   6],
       [  7, 200,   9]])

In [5]:
arr=np.zeros(5)
arr

array([0., 0., 0., 0., 0.])

In [7]:
arr=np.arange(1,9)
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [8]:
arr.reshape(2,4)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [9]:
arr=np.arange(0,21,2)
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [11]:
arr=np.linspace(0,1,8)
arr

array([0.        , 0.14285714, 0.28571429, 0.42857143, 0.57142857,
       0.71428571, 0.85714286, 1.        ])

In [13]:
arr.shape

(3, 3)

In [16]:
arr.itemsize

8

In [18]:
arr=np.zeros((4,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [20]:
arr.shape


(4, 3)

In [22]:
arr.size


12

In [23]:
arr.dtype


dtype('float64')

In [24]:
arr.ndim

2

In [26]:
arr.flatten()

array([  1,   2,   3,   4,   5,   6,   7, 200,   9])

In [27]:
arr.astype(float)

array([[  1.,   2.,   3.],
       [  4.,   5.,   6.],
       [  7., 200.,   9.]])

In [29]:
arr.max()

np.int64(200)

In [30]:
arr=np.array([[1,2],[3,4]])
arr

array([[1, 2],
       [3, 4]])

In [35]:
arr.reshape(4,)

array([1, 2, 3, 4])

In [32]:
arr.reshape(4,1)

array([[1],
       [2],
       [3],
       [4]])

In [33]:
arr.flatten()

array([1, 2, 3, 4])

In [37]:
np.sum(arr,axis=1)

array([  6,  15, 216])

In [38]:
np.sum(arr,axis=0)

array([ 12, 207,  18])