In [1]:
import numpy as np

In [2]:
arr=np.array([10,20,30,40,50])
arr

array([10, 20, 30, 40, 50])

In [3]:
arr=np.array([[1,2,3],[4,5,6],[7,200,9]])
arr

array([[  1,   2,   3],
       [  4,   5,   6],
       [  7, 200,   9]])

In [4]:
arr=np.zeros(5)
arr

array([0., 0., 0., 0., 0.])

In [5]:
arr=np.arange(1,9)
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [6]:
arr.reshape(2,4)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [26]:
arr=np.arange(0,19,2).reshape(2,5)
arr

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [8]:
arr=np.linspace(0,1,8)
arr

array([0.        , 0.14285714, 0.28571429, 0.42857143, 0.57142857,
       0.71428571, 0.85714286, 1.        ])

In [9]:
arr.shape

(8,)

In [10]:
arr.itemsize

8

In [11]:
arr=np.zeros((4,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [12]:
arr.shape


(4, 3)

In [13]:
arr.size


12

In [14]:
arr.dtype


dtype('float64')

In [15]:
arr.ndim

2

In [16]:
arr.flatten()

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [17]:
arr.astype(float)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [18]:
arr.max()

np.float64(0.0)

In [19]:
arr=np.array([[1,2],[3,4]])
arr

array([[1, 2],
       [3, 4]])

In [20]:
arr.reshape(4,)

array([1, 2, 3, 4])

In [21]:
arr.reshape(4,1)

array([[1],
       [2],
       [3],
       [4]])

In [22]:
arr.flatten()

array([1, 2, 3, 4])

In [23]:
np.sum(arr,axis=1)

array([3, 7])

In [24]:
np.sum(arr,axis=0)

array([4, 6])