In [1]:
import numpy as np

In [2]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([6,7,8,9,10])

In [3]:
#arithmatic operations on array
arr1+arr2

array([ 7,  9, 11, 13, 15])

In [4]:
arr1 * arr2

array([ 6, 14, 24, 36, 50])

In [5]:
arr2/arr1

array([6.        , 3.5       , 2.66666667, 2.25      , 2.        ])

In [6]:
arr2//arr1

array([6, 3, 2, 2, 2])

In [7]:
#Broadcasting 
#adding some number to a array elements
arr1+12

array([13, 14, 15, 16, 17])

In [8]:
#Broadcasting 
#performing arithmatic operations on 1D and 2D arrays
arr3=np.arange(1,11).reshape(2,5)
arr3


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [9]:
arr1+arr3

array([[ 2,  4,  6,  8, 10],
       [ 7,  9, 11, 13, 15]])

In [10]:
arr1*arr3

array([[ 1,  4,  9, 16, 25],
       [ 6, 14, 24, 36, 50]])

In [11]:
arr2*arr3

array([[  6,  14,  24,  36,  50],
       [ 36,  49,  64,  81, 100]])

In [12]:
#Deep and shallow copy 
arr=np.arange(1,21)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [13]:
#deep copy
#when you change sliced part of array it does not change orignal array because the sliced part is stored at seperated memory location
Slice=arr[:5]
Slice

array([1, 2, 3, 4, 5])

In [14]:
Slice *2

array([ 2,  4,  6,  8, 10])

In [15]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [16]:
#shallow copy
#when you change sliced part in deep copy ,it will change the orignal array because this sliced part are stored in same memory location
b=arr.view()
b[0:2]=[23,34]

In [17]:
b

array([23, 34,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])