In [1]:
import numpy as np

In [2]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
arr.min()


np.int64(1)

In [6]:
arr.max()

np.int64(9)

In [7]:
arr.sum()

np.int64(45)

In [8]:
#sum of rows in numpy arrays
np.sum(arr,axis=1)

array([ 6, 15, 24])

In [9]:
#sum of column in numpy arrays
np.sum(arr,axis=0)

array([12, 15, 18])

In [11]:
arr.mean()

np.float64(5.0)

In [12]:
arr.std()

np.float64(2.581988897471611)

In [13]:
arr.argmin()

np.int64(0)