**Valid Sudoku**

In [1]:
import numpy as np

In [2]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [3]:
s[0:3,0:3]

array([[5, 3, 4],
       [6, 7, 2],
       [1, 9, 8]])

In [15]:
np.vsplit(s,9)

[array([[5, 3, 4, 6, 7, 8, 9, 1, 2]]),
 array([[6, 7, 2, 1, 9, 5, 3, 4, 8]]),
 array([[1, 9, 8, 3, 4, 2, 5, 6, 7]]),
 array([[8, 5, 9, 7, 6, 1, 4, 2, 3]]),
 array([[4, 2, 6, 8, 5, 3, 7, 9, 1]]),
 array([[7, 1, 3, 9, 2, 4, 8, 5, 6]]),
 array([[9, 6, 1, 5, 3, 7, 2, 8, 4]]),
 array([[2, 8, 7, 4, 1, 9, 6, 3, 5]]),
 array([[3, 4, 5, 2, 8, 6, 1, 7, 9]])]

In [16]:
b=np.sum(s,axis=0)
b

array([45, 45, 45, 45, 45, 45, 45, 45, 45])

In [ ]:
for i in b:
    if i!=45:
        print("The sudoku is Invalid")
        break
else:
 print("Valid Sudoku")


Valid Sudoku


In [20]:
b=s[0:3,0:3]

In [21]:
b.sum()

np.int64(45)

In [24]:
for i in range(0,9,3):
    for j in range(0,9,3):
        print(s[i:i+3,j:j+3])

[[5 3 4]
 [6 7 2]
 [1 9 8]]
[[6 7 8]
 [1 9 5]
 [3 4 2]]
[[9 1 2]
 [3 4 8]
 [5 6 7]]
[[8 5 9]
 [4 2 6]
 [7 1 3]]
[[7 6 1]
 [8 5 3]
 [9 2 4]]
[[4 2 3]
 [7 9 1]
 [8 5 6]]
[[9 6 1]
 [2 8 7]
 [3 4 5]]
[[5 3 7]
 [4 1 9]
 [2 8 6]]
[[2 8 4]
 [6 3 5]
 [1 7 9]]


**General Questions**

In [59]:
import numpy as np

# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

In [26]:
#Get the shape of the matrix.
data.shape

(5, 3)

In [29]:
#Find the average age of students.
np.mean(data[0:,0:1])

np.float64(18.4)

In [30]:
#Extract Math marks of all students.
data[0:,1]

array([85, 92, 76, 65, 90])

In [31]:
#Find the highest Science mark.
np.max(data[0:,2])

np.int64(95)

In [35]:
#Get details of the student who scored more than 90 in Math.

b=data[0:,1]
bolean_index=b>90
bolean_index
b[bolean_index]

array([92])

In [39]:
#Increase Math marks of all students by 5.
data[0:,1] +=5
data


array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70, 70],
       [20, 95, 85]])

In [50]:
#Find how many students are younger than 19.
len(data[data[:,0]<19])

3

In [52]:
#Calculate the average marks in each subject (column-wise mean).
np.mean(data[:,1:],axis=0)

array([86.6, 83.2])

In [55]:
#Get data of students who scored at least 80 in both subjects.
data[(data[:,1]>=80) & (data[:,2]>=80)]



array([[19, 97, 88],
       [17, 81, 95],
       [20, 95, 85]])

In [ ]:
#Replace all Science marks < 75 with 0.
data[:,2][data[:,2]<75]=0
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65,  0],
       [20, 90, 85]])