In [1]:
import numpy as np

In [2]:
arr=np.arange(12,26)
arr

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25])

In [3]:
arr[5]

np.int64(17)

In [4]:
arr[5]=10
arr

array([12, 13, 14, 15, 16, 10, 18, 19, 20, 21, 22, 23, 24, 25])

In [5]:
arr[4:9]

array([16, 10, 18, 19, 20])

In [6]:
arr.argmax()

np.int64(13)

In [7]:
arr[0:12:2]

array([12, 14, 16, 18, 20, 22])

In [8]:
arr[4:12]

array([16, 10, 18, 19, 20, 21, 22, 23])

In [9]:
arr

array([12, 13, 14, 15, 16, 10, 18, 19, 20, 21, 22, 23, 24, 25])

In [10]:
#Indexing and slicing of Matrix
Matrix=np.arange(1,31).reshape(6,5)
Matrix

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [11]:
#for finding row in 2D array
Matrix[0]

array([1, 2, 3, 4, 5])

In [12]:
Matrix[3]

array([16, 17, 18, 19, 20])

In [13]:
Matrix[0,4]

np.int64(5)

In [14]:
#Finding the elemment in the 2D array
Matrix[3,2]

np.int64(18)

In [15]:
#for finding the portion in the 2Darray
Matrix[2:4,2:4]

array([[13, 14],
       [18, 19]])

In [16]:
Matrix

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [17]:
Matrix[2:5,2:]

array([[13, 14, 15],
       [18, 19, 20],
       [23, 24, 25]])

In [18]:
Matrix[:,0]

array([ 1,  6, 11, 16, 21, 26])

In [19]:
Matrix[:,1]

array([ 2,  7, 12, 17, 22, 27])

In [20]:
arr=np.arange(10,20)

In [21]:
bool_index=arr %2==0
bool_index

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [22]:
#boolean Indexing
arr[bool_index]

array([10, 12, 14, 16, 18])