In [2]:
import numpy as np

In [3]:
arr=np.arange(1,33)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32])

In [4]:
Array=arr.reshape(8,4)

In [5]:
Array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [6]:
arr=np.arange(1,26).reshape(5,5)

In [7]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [8]:
arr[2:4,1:3]

array([[12, 13],
       [17, 18]])

In [9]:
arr[2:4,2:4]

array([[13, 14],
       [18, 19]])